### ISSUE TITLE
Entity Master: initial instantiation of simple entity masters is slow in the development workflow

### ISSUE THREAD

**Issue by 01es** [fieldenms/tg#1809]
### Description

A significant delay is observer upon initial invocation of a Simple Entity Master, which affects only the `development` workflow.
No performance degradation is observed for Compound Entity Masters. This is most likely related to the most recent changes in the area of determining correspondence between entity types and simple masters. 

Although this does not affect the `deployment` workflow, improving the speed of the initial invocation for Simple Entity Masters in the `development` workflow would be extremely helpful to improve development productivity and reduce frustration.

### Expected outcome
Improved development productivity.

**Comment by oleh-maikovych** [comment]
A sinificant delay upon initial invocation of Simple Master is caused by the first instatntiation of `SecurityTokenProvider`. This happens only once, because `SecurityTokenProvider` is singletone and it is instantiated only once, when user opens simple master first time. After that all simple masters get opened without delay. This effect can be observerd only in `development` mode.
