### ISSUE TITLE
Entity Centre: contextual user definable help

### ISSUE THREAD

**Issue by 01es** [fieldenms/tg#1960]
### Description

Similarly to #1955 support for contextual user definable help is also required for Entity Centres – both standalone and embedded. 
But unlike masters, help for Entity Centres needs to be associated with menu items, which will server as the unique key for `EntityCentreHelp`.

The "help" action should be present in selection criteria and EGI as depicted below.

<img width="1283" alt="image" src="https://user-images.githubusercontent.com/5511940/232378008-050ecec2-3234-43f0-887e-f20dafd088dc.png">

One complication for Entity Centres if the ability to provide alternative views, which may have their own toolbars. There needs to an easy-to-use API for adding the "help" action to such toolbars. Please note that the same help is assumed to be applicable to all views of the same Entity Centre. As an example, please consider GIS View below.

<img width="1168" alt="image" src="https://user-images.githubusercontent.com/5511940/232377279-8bf2bbe1-2ceb-45cb-bba7-bbd871c438dd.png">

### Expected outcome
Ability for users to associate/open an external resource, representing help, with any Entity Centre.

**Comment by oleh-maikovych** [comment]
This is issue was implemented according to requirements. But new requirement has arised after this issue was closed. The help action should provide default URI if there wasn't any specified. This default help URI should be configured in `application.properties` with `help.defaultUri` property. It should be binded in `UserDefinableHelpProducer` constructor and should be used if there is no any `UserDefinableHelp` instance associated with current `referenceElement`
